TITLE-------Nome: Augusto Guaschi Morato RA:22008248
.model small 
SOMETUDO MACRO      ;macro de apagar tudo da tela
        MOV AX,3
        INT 10H
    ENDM
Pular MACRO; macro para Pular Linha 
    MOV AH,2
    MOV DL,10 ; pular a linha 
    INT 21h   
ENDM

.stack 100h
.data
msg db 'Maiusculo: $'
msg1 db 'Minusculo: $'
.Code   
main proc
SOMETUDO
MOV AX,@DATA
MOV DS,AX

Mov Bl,64
Mov CX,13

MOV AH,9 ;
LEA DX,msg; exibe a mensagem na tela 
INT 21h;
MAI1:
Dec CX ;USAMOS O CX COMO CONTADOR 
inc BL ;ADICIONAMOS UM EM BL A CADA LOOP
MOV AH,2
MOV DL,BL
INT 21h ;IMPRMIMOS 
CMP Cx,0
JNE MAI1 ; CASO CX NÃO SEJA 0 IRA REPETIR


MAi2:; A SEGUNDA VOLA SERA FEITA COM AS ULTIMOS 13 LETRAS 
inc CX; CONTINUAMOS A USAR O CX COMO CONTADOR 
inc BL; VAMOS ADICIONANDO 1 EM BL PARA IMPRIMIR AS OUTRAS LETRAS 
MOV AH,2
MOV DL,BL; IMPRIME OS NUMEROS 
INT 21h 
CMP CX,13; CASO SEJA DIFERENTE DE 13 EM CX RETORNA
JNE MAI2 

mov aH,01
INT 21h; USAMOS PARA COLOCAR UM "ENTER" NO PROGRAMA

MOV BL,96 ; USAMOS BL COMO 96 PARA IMPRIMIR OS MINUSCULOS 

Pular ;PULAR A LINHA 

MOV AH,9 ;
LEA DX,msg1; MENSAGEM INFORMANDO SOBRE 
INT 21h;

MIN1:;LOOP DOS 13 PRIMEIROS MINUSCULOS 
Dec CX
inc BL
MOV AH,2
MOV DL,BL
INT 21h 
CMP CX,0
JNE MIN1 

MIN2:; LOOP DOS 13 ULTIMOS MINUSCULOS 
inc CX
inc BL
MOV AH,2
MOV DL,BL
INT 21h 
CMP CX,13
JNE MIN2 

MOV AH,4Ch
INT 21h
main ENDP
end main



